// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcc4HslJhPWRjFSnA48EVjbA3m15jxfI8',
    appId: '1:948207748221:web:4303a60db0fb834ccf5d14',
    messagingSenderId: '948207748221',
    projectId: 'instagram-clone-3ca93',
    authDomain: 'instagram-clone-3ca93.firebaseapp.com',
    storageBucket: 'instagram-clone-3ca93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmc4DzM1BYHYZUIu0iboyw_9TTLbCCHrI',
    appId: '1:948207748221:android:ee043b8a2c172a9dcf5d14',
    messagingSenderId: '948207748221',
    projectId: 'instagram-clone-3ca93',
    storageBucket: 'instagram-clone-3ca93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJYXLNMet4svlvKP7DZ9iMo3HtSENdYAs',
    appId: '1:948207748221:ios:4573aad8ad6b7ba1cf5d14',
    messagingSenderId: '948207748221',
    projectId: 'instagram-clone-3ca93',
    storageBucket: 'instagram-clone-3ca93.appspot.com',
    iosClientId: '948207748221-q93e2ib5eiel3hus97371scilbs37ifj.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
